//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmy()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int ID_Filmu { get; set; }
        public string Tytul { get; set; }
        public int ID_Rezysera { get; set; }
        public int ID_Aktora { get; set; }
        public string Gatunek { get; set; }
        public int Czas_trwania { get; set; }
        public string Stan { get; set; }
    
        public virtual Aktor Aktor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
        public virtual Rezyser Rezyser { get; set; }
    }
}
