//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int ID_Wypozyczenia { get; set; }
        public int ID_Filmu { get; set; }
        public int ID_Klienta { get; set; }
        public int ID_Kuriera { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public string DataZwtotu { get; set; }
    
        public virtual Filmy Filmy { get; set; }
        public virtual Klienci Klienci { get; set; }
        public virtual Kurier Kurier { get; set; }
    }
}
